export const variables = {
	LOGIN_URL: 'http://localhost:3000/login',
	LOGIN_SECOND_FACTOR: 'http://localhost:3000/loginSecondFactor',
	REGISTER_URL: 'http://localhost:3000/register',
	IS_AUTHENTICATED: 'http://localhost:3000/isAuthenticated',
	GET_USER_INFO: 'http://localhost:3000/getUserInfo',
	REVOKE_TOKEN: 'http://localhost:3000/revokeToken',
	GET_QR_CODE: 'http://localhost:3000/getQrCode',
	VALIDATE_QR_CODE: 'http://localhost:3000/validateQrCode',
	CHANGE_TWO_FACTOR_AUTH: 'http://localhost:3000/changeTwoFactorAuth',
	GET_PRODUCT_BY_ID: 'http://localhost:3000/getProductById',
	GET_PRODUCTS: 'http://localhost:3000/getProducts',
	ADD_PRODUCT: 'http://localhost:3000/insertProduct',
	UPDATE_PRODUCT: 'http://localhost:3000/updateProduct',
	DELETE_PRODUCT: 'http://localhost:3000/deleteProduct',

	LOGIN_PAGE: '/',
	REGISTER_PAGE: '/register',
	DASHBOARD_PAGE: '/dashboard',
	TOTP_REQUIRE: '/totprequire',
	TOTP_ACTIVATE: '/totpactivate',
	PRODUCT_BY_ID: '/product/:id',
	INVALID_PATH: '*',
}
